/** Renders a JSON-LD structured data script. Server component (no client JS). */
export default function JsonLd({
  data,
  id,
}: {
  data: Record<string, unknown>;
  id?: string;
}) {
  return (
    <script
      id={id}
      type="application/ld+json"
      // JSON-LD must be a raw script; this content is generated by us, not users.
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
